<a href="https://colab.research.google.com/github/nidhi543/MCA/blob/main/LabEval_group2_202301039.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [12]:
arr1 = np.array([10,52,62,16,16,54,453])
arr2 = np.sort(arr1)
print(arr2)

[ 10  16  16  52  54  62 453]


In [22]:
indices = np.argsort(arr1)
print(indices)

[0 3 4 1 5 2 6]


In [14]:
arr3 = arr2[0:4]
print(arr3)

[10 16 16 52]


In [20]:
arr4 =  arr1[indices[-5:]]
print(arr4)

[ 16  52  54  62 453]
