<a href="https://colab.research.google.com/github/nidhi543/MCA/blob/main/numpyASS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,6,4,5])
arr_r = np.flip(arr)
arr_r

array([5, 4, 6, 3, 2, 1])

In [7]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1,2], [3,4]])
print((arr1==arr2).all())

True


In [20]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
#find frequency of each value
values, counts = np.unique(x, return_counts=True)

print(values)
print(counts)

#display value with highest frequency
elements = values[counts == counts.max()]

print(elements)

indices = []

for i in range(0, len(x)) :
  if x[i] in elements:
      indices.append(i)

print(indices)

[1 2 3 4 5]
[5 2 1 1 1]
[1]
[0, 5, 7, 8, 9]


In [19]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
#find frequency of each value
values, counts = np.unique(x, return_counts=True)

print(values)
print(counts)

#display value with highest frequency
elements = values[counts == counts.max()]

print(elements)

indices = []

for i in range(0, len(x)) :
  if x[i] in elements:
      indices.append(i)

print(indices)



[1 2 3 4]
[3 2 3 2]
[1 3]
[0, 1, 2, 4, 8, 9]


In [26]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
s= np.sum(gfg)
rs=np.sum(gfg,axis=1)
cs=np.sum(gfg,axis=0)
print("Sum of all elements:", s)
print("Sum of all elements row-wise",rs)
print("Sum of all elements column-wise",cs)

Sum of all elements: 45
Sum of all elements row-wise [[14]
 [16]
 [15]]
Sum of all elements column-wise [[20  9 16]]
